'use strict'

var gImgs = [
    { id: 1, url: "./meme-imgs/1.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 2, url: "./meme-imgs/2.jpg", keywords: ['puppy', 'dog', 'cute', 'love'] },
    { id: 3, url: "./meme-imgs/3.jpg", keywords: ['puppy', 'baby', 'love','friendship', 'sleep'] },
    { id: 4, url: "./meme-imgs/4.jpg", keywords: ['cat', 'computer','work','sleep','keyboard', 'cute'] },
    { id: 5, url: "./meme-imgs/5.jpg", keywords: ['baby', 'strong', 'win','power', 'winner','funny'] },
    { id: 6, url: "./meme-imgs/6.jpg", keywords: ['funny', 'history','teacher','movie']},
    { id: 7, url: "./meme-imgs/7.jpg", keywords: ['baby','funny','suprise','eyes'] },
    { id: 8, url: "./meme-imgs/8.jpg", keywords: ['funny', 'charlie','listening','movie'] },
    { id: 9, url: "./meme-imgs/9.jpg", keywords: ['baby', 'plan', 'laugh', 'laughter','evil'] },
    { id: 10, url: "./meme-imgs/10.jpg", keywords: ['barak obama', 'laugh', 'laughter', 'funny'] },
    { id: 11, url: "./meme-imgs/11.jpg", keywords: ['wrestling', 'black','kiss','angry'] },
    { id: 12, url: "./meme-imgs/12.jpg", keywords: ['haim echt','what would you do','funny','responsibility'] },
    { id: 13, url: "./meme-imgs/13.jpg", keywords: ['leonardo dicaprio', 'cheers','toast','happy', 'movie'] },
    { id: 14, url: "./meme-imgs/14.jpg", keywords: ['matrix','new world','black','movie'] },
    { id: 15, url: "./meme-imgs/15.jpg", keywords: ['lord of the rings','movie','understand','hole','zero'] },
    { id: 16, url: "./meme-imgs/16.jpg", keywords: ['star trek','star wars', 'sigh','movie','laugh','laughter']},
    { id: 17, url: "./meme-imgs/17.jpg", keywords: ['putin', 'politics','suit','two','leader'] },
    { id: 18, url: "./meme-imgs/18.jpg", keywords: ['toy story','buzz','woody','movie', 'cartoon','friendship'] },{ id: 1, url: "./meme-imgs/1.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 19, url: "./meme-imgs/19.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 20, url: "./meme-imgs/20.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 21, url: "./meme-imgs/drevil.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 22, url: "./meme-imgs/img2.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 23, url: "./meme-imgs/img4.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 24, url: "./meme-imgs/img5.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 25, url: "./meme-imgs/img6.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 26, url: "./meme-imgs/img11.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 27, url: "./meme-imgs/img12.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 28, url: "./meme-imgs/leo.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 29, url: "./meme-imgs/meme1.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 30, url: "./meme-imgs/One-Does-Not-Simply.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 31, url: "./meme-imgs/Oprah-You-Get-A.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 32, url: "./meme-imgs/patrick.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 33, url: "./meme-imgs/putin.jpg", keywords: ['politics', 'trump','suit','angry']},
    { id: 34, url: "./meme-imgs/X-Everywhere.jpg", keywords: ['politics', 'trump','suit','angry']},
]
_saveImgsToStorage()
